[package]
authors = ["Nathan Ringo <remexre@gmail.com>"]
edition = "2018"
name = "stahl_value"
version = "0.1.0"

[dependencies]
derivative = "1.0.2"
proptest = { version = "0.8.7", optional = true }
stahl_errors = { path = "../errors" }
stahl_util = { path = "../util" }
