language: minimal
os: linux
services:
- docker
cache:
  bundler: true
  directories:
    - $HOME/docker

before_install:
- if [[ -e $HOME/docker/stahl-builder.tgz ]]; then zcat $HOME/docker/stahl-builder.tgz | docker load; fi
- docker build -t remexre/stahl-builder .travis

script:
- if [[ $TRAVIS_EVENT_TYPE = cron ]]; then \
    docker run -v "$PWD:/code" --rm remexre/stahl-builder make ci-cron-inner \
  else \
    docker run -v "$PWD:/code" --rm remexre/stahl-builder make ci-inner \
  fi

before_cache:
- mkdir -p $HOME/docker
- docker save remexre/stahl-builder $(docker history -q remexre/stahl-builder | grep -v missing) | gzip > $HOME/docker/stahl-builder.tgz

deploy:
- provider: releases
  api_key: $GITHUB_TOKEN
  file: out/stahl.fth
  on:
    tags: true
  skip_cleanup: true
