language: haskell
fast_finish: true
os: linux
cache:
  directories:
  - $HOME/.cabal
  - dist
  - dist-newstyle

install:
- curl -L 'https://github.com/rust-lang-nursery/mdBook/releases/download/v0.2.1/mdbook-v0.2.1-x86_64-unknown-linux-musl.tar.gz' | tar zxC /tmp mdbook

script:
- cabal v2-test
- /tmp/mdbook test docs

before_deploy:
- /tmp/mdbook build docs
deploy:
- provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: docs/book
  keep-history: false
  on:
    branch: master
