[package]
authors = ["Nathan Ringo <remexre@gmail.com>"]
edition = "2018"
name = "stahl_cst"
version = "0.1.0"

[dependencies]
derivative = "1.0.2"
stahl_errors = { path = "../errors" }
stahl_parser = { path = "../parser" }
stahl_util = { path = "../util" }
