[package]
authors = ["Nathan Ringo <remexre@gmail.com>"]
edition = "2018"
name = "stahl_ast"
version = "0.1.0"

[dependencies]
stahl_errors = { path = "../errors" }
stahl_parser = { path = "../parser" }
